### ISSUE TITLE
Readme/Documentation is opaque and unclear

### ISSUE THREAD

**Issue by hmswaffles** [harsh19/Shakespearizing-Modern-English#2]
For better and for worse, the Readme file leaves a lot for the reader to infer. 

I suggest that it:
a) have an industry standard requirements file, that tells people this codebase is written in ```Python 2```,
b) contain a link to the [modern Python3 Version ](https://github.com/guotong1988/Shakespearizing-python3/tree/master/code)
c) note the file path which is hardcoded in the `config.py file`
d) make clear the relationship between the training, test, and val files. In particular, if one wants to try a trained shakespearizer model on novel text, the documentation should direct where should one put one's quote OOV unquote sentences.
e) be updated so that bullet points which symbolize code are instead wrapped with three backticks (```) to make them more readable

**Comment by harsh19** [comment]
Hi,
Thanks for showing interest in our work.
We have updated the documentation accordingly, and tried to incorporate as many suggestions as possible.
